apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-v3io-fuse
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sparkoperator.name" . }}
    helm.sh/chart: {{ include "sparkoperator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: v3io/fuse
data:
  username: {{ .Values.v3io.username | quote}}
  accessKey: {{ .Values.v3io.accessKey | quote }}

